name: pages action

on:
    push:
        branches: -main
    workflow_dispatch:

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Hello World
              run: echo "Hellow World"
              shell: bash
